# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('dateCreated', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
