# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='forums',
            new_name='Forum',
        ),
    ]
