# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20170427_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
