# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20170427_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=200)),
                ('dateAnswered', models.DateTimeField(default=datetime.datetime.now)),
                ('upVote', models.IntegerField(default=0)),
                ('downVote', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='downVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='upVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forums.Forum'),
        ),
    ]
