# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20170429_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
