# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20170429_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
