# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20170429_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='downVote',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='downVote',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upVote',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='upVote',
        ),
    ]
