# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20170429_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dateAnswered',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='dateCreated',
        ),
    ]
