# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_auto_20170507_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dateAnswered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='forum',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
