# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_answer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='count',
        ),
        migrations.AddField(
            model_name='forum',
            name='ansCount',
            field=models.IntegerField(default=0),
        ),
    ]
