# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_auto_20170514_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Forum'),
        ),
    ]
