# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_auto_20170514_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='ansCount',
        ),
    ]
