# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_auto_20170514_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
