# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0016_auto_20170514_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='acceptedAns',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='solved',
        ),
    ]
