# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170423_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='probAttemped',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='probSolved',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='', upload_to=b''),
        ),
    ]
