# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('submissions', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
            ],
        ),
    ]
