# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='pid',
        ),
        migrations.AlterField(
            model_name='problemset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
