# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170422_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
