# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problemset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='constraints',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='problemset',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='problemset',
            name='inputDesc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='problemset',
            name='outputDesc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
