# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20170507_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='problemSetter',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='problemset',
            name='problemTester',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='problemset',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='problemset',
            name='timeLimit',
            field=models.FloatField(default=0.0),
        ),
    ]
