# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20170507_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='constraints',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='inputDesc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='outputDesc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='problemSetter',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='problemTester',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
