# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20170507_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='publishDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
