# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_auto_20170507_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
