# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20170507_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='publishDate',
        ),
    ]
