# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20170507_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='inputDesc',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='outputDesc',
        ),
    ]
